before_install:
- openssl aes-256-cbc -K $encrypted_4a21bc166b29_key -iv $encrypted_4a21bc166b29_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv application-prod.yml src/main/resources/config/application-prod.yml
- mv deploy_rsa /tmp/deploy_rsa
language: java
node_js:
  - "9"
script:
- mvn clean package -Pprod
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - $HOME/.m2
addons:
  ssh_known_hosts: 104.236.26.235
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: rsync --quiet $TRAVIS_BUILD_DIR/target/theBuyback*.war buyback@104.236.26.235:~ && ssh-agent -k
  on:
    tags: true
